name: ${project.name}
main: com.github.maxopoly.caveworm.Caveworm
author: Maxopoly
version: ${project.version}
api-version: 1.13
commands:
    cwgen:
      permission: cw.op
    cwreload:
      permission: cw.op
    cwseed:
      permission: cw.op
    cwmultiseed:
      permission: cw.op
permissions:
    cw.op:
        default: op